In [ ]:
import pandas as pd
import numpy as np
import os

In [ ]:
df=pd.read_csv('olist_geolocation_dataset.csv')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 192256 entries, 0 to 192255
Data columns (total 5 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   geolocation_zip_code_prefix  192256 non-null  int64
 1   geolocation_lat              192256 non-null  float64
 2   geolocation_lng              192255 non-null  float64
 3   geolocation_city             192255 non-null  object
 4   geolocation_state            192255 non-null  object
dtypes: float64(2), int64(1), object(2)
memory usage: 7.3+ MB

In [ ]:
df.isnull().sum()

geolocation_zip_code_prefix    0
geolocation_lat                0
geolocation_lng                0
geolocation_city               0
geolocation_state              0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(261831)

In [ ]:
df.head(10)

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,sao paulo,SP
1,1046,-23.546081,-46.644820,sao paulo,SP
2,1046,-23.546129,-46.642951,sao paulo,SP
3,1041,-23.544392,-46.639499,sao paulo,SP
4,1035,-23.541578,-46.641607,sao paulo,SP
5,1012,-23.547762,-46.635361,são paulo,SP
6,1047,-23.546273,-46.641225,sao paulo,SP
7,1013,-23.546923,-46.634264,sao paulo,SP
8,1029,-23.543769,-46.634278,sao paulo,SP
9,1011,-23.547640,-46.636032,sao paulo,SP

In [ ]:
df = df.drop(columns=['geolocation_lat', 'geolocation_lng'])

In [ ]:
df

         geolocation_zip_code_prefix geolocation_city geolocation_state
0                               1037        sao paulo                SP
1                               1046        sao paulo                SP
2                               1046        sao paulo                SP
3                               1041        sao paulo                SP
4                               1035        sao paulo                SP
...                              ...              ...               ...
1000158                        99950         tapejara                RS
1000159                        99900   getulio vargas                RS
1000160                        99950         tapejara                RS
1000161                        99980  david canabarro                RS
1000162                        99950         tapejara                RS

[1000163 rows x 3 columns]

In [ ]:
df["geolocation_city"]

0                sao paulo
1                sao paulo
2                sao paulo
3                sao paulo
4                sao paulo
                ...
1000158           tapejara
1000159     getulio vargas
1000160           tapejara
1000161    david canabarro
1000162           tapejara
Name: geolocation_city, Length: 1000163, dtype: object

In [ ]:
df['geolocation_city'].unique()

array(['sao paulo', 'são paulo', 'sao bernardo do campo', ..., 'ciríaco',
       'estação', 'vila lângaro'], dtype=object)

In [ ]:
df["geolocation_city"] = df["geolocation_city"].replace({
    "taboão da serra": "taboao da serra",
    "sãopaulo": "sao paulo",
    "sa£o paulo": "sao paulo",

    "caraguatatuba": "caraguatatuba",
    "carapicuíba": "carapicuiba",

    "santana de parnaíba": "santana de parnaiba",

    "são lourenço da serra": "sao lourenco da serra",

    "embu-guaçu": "embu guacu",
    "embu-guacu": "embu guacu",
    "embu guaçu": "embu guacu",
    "embu guacu": "embu guacu",
    "embuguacu": "embu guacu",

    "guarulhos-sp": "guarulhos",
    "arujá": "aruja",
    "mairiporã": "mairipora",

    "jordanésia": "jordanesia",
    "mauá": "maua"
})

In [ ]:
df['geolocation_city'].unique()

array(['sao paulo', 'são paulo', 'sao bernardo do campo', ..., 'ciríaco',
       'estação', 'vila lângaro'], dtype=object)

In [ ]:
df["geolocation_city"] = df["geolocation_city"].replace({
    "são paulo": "sao paulo",
    "sp": "sao paulo"
})

In [ ]:
df['geolocation_city'].unique()

array(['sao paulo', 'sao bernardo do campo', 'jundiaí', ..., 'ciríaco',
       'estação', 'vila lângaro'], dtype=object)

In [ ]:
df["geolocation_city"] = df["geolocation_city"].replace({
    "jundiaí": "jundiai",
    "são paulo": "sao paulo",
    "sp": "sao paulo"
})

In [ ]:
df['geolocation_city'].unique()

array(['sao paulo', 'sao bernardo do campo', 'jundiai', ..., 'ciríaco',
       'estação', 'vila lângaro'], dtype=object)

In [ ]:
print(df.duplicated().sum())

975418

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000163 entries, 0 to 1000162
Data columns (total 3 columns):
 #   Column                       Non-Null Count    Dtype
---  ------                       --------------    -----
 0   geolocation_zip_code_prefix  1000163 non-null  int64
 1   geolocation_city             1000163 non-null  object
 2   geolocation_state            1000163 non-null  object
dtypes: int64(1), object(2)
memory usage: 22.9+ MB

In [ ]:
df['geolocation_zip_code_prefix'].duplicated().sum()

np.int64(981148)

In [ ]:
from google.colab import files

df.to_csv('cleaned_olist_geolocation.csv', index=False, encoding='utf-8-sig')
files.download('cleaned_olist_geolocation.csv')

Products cleaning

In [ ]:
products=pd.read_csv('olist_products_dataset.csv')

In [ ]:
products.head(10)

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0
5,41d3672d4792049fa1779bb35283ed13,instrumentos_musicais,60.0,745.0,1.0,200.0,38.0,5.0,11.0
6,732bd381ad09e530fe0a5f457d81becb,cool_stuff,56.0,1272.0,4.0,18350.0,70.0,24.0,44.0
7,2548af3e6e77a690cf3eb6368e9ab61e,moveis_decoracao,56.0,184.0,2.0,900.0,40.0,8.0,40.0
8,37cc742be07708b53a98702e77a21a02,eletrodomesticos,57.0,163.0,1.0,400.0,27.0,13.0,17.0
9,8c92109888e8cdf9d66dc7e463025574,brinquedos,36.0,1156.0,1.0,600.0,17.0,10.0,12.0

In [ ]:
products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29048 entries, 0 to 29047
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  29048 non-null  object
 1   product_category_name       28516 non-null  object
 2   product_name_lenght         28515 non-null  float64
 3   product_description_lenght  28515 non-null  float64
 4   product_photos_qty          28515 non-null  float64
 5   product_weight_g            29045 non-null  float64
 6   product_length_cm           29045 non-null  float64
 7   product_height_cm           29045 non-null  float64
 8   product_width_cm            29045 non-null  float64
dtypes: float64(7), object(2)
memory usage: 2.0+ MB

In [ ]:
products.isnull().sum()

product_id                      0
product_category_name         532
product_name_lenght           533
product_description_lenght    533
product_photos_qty            533
product_weight_g                3
product_length_cm               3
product_height_cm               3
product_width_cm                3
dtype: int64

In [ ]:
products.rename(
    columns={
        "product_name_lenght": "product_name_length",
        "product_description_lenght": "product_description_length",
    },
    inplace=True,
)

In [ ]:
products["product_category_name"] = products["product_category_name"].fillna("unknown")
products["product_photos_qty"] = products["product_photos_qty"].fillna(0)
products["product_name_length"] = products["product_name_length"].fillna(0)
products["product_description_length"] = products["product_description_length"].fillna(0)

In [ ]:
products.isnull().sum()

product_id                    0
product_category_name         0
product_name_length           0
product_description_length    0
product_photos_qty            0
product_weight_g              3
product_length_cm             3
product_height_cm             3
product_width_cm              3
dtype: int64

In [ ]:
import pandas as pd
all_cols = [
    'product_weight_g',
    'product_length_cm',
    'product_height_cm',
    'product_width_cm',
]


for col in all_cols:
    products[col] = products[col].fillna(
        products.groupby('product_category_name')[col].transform('median')
    )


    products[col] = products[col].fillna(products[col].median())

In [ ]:
products.isnull().sum()

product_id                    0
product_category_name         0
product_name_length           0
product_description_length    0
product_photos_qty            0
product_weight_g              0
product_length_cm             0
product_height_cm             0
product_width_cm              0
dtype: int64

In [ ]:
products.duplicated().sum()

np.int64(0)

In [ ]:
products['product_id'].duplicated().sum()

np.int64(0)

In [ ]:
products.to_csv('cleaned_products.csv', index=False, encoding='utf-8-sig')